"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.THESAURI_SAVED = exports.THESAURI_DELETED = exports.SET_THESAURIS = exports.RESET_THESAURI = exports.EDIT_THESAURI = void 0; //DATA
const THESAURI_SAVED = 'THESAURI_SAVED';exports.THESAURI_SAVED = THESAURI_SAVED;
const EDIT_THESAURI = 'EDIT_THESAURI';exports.EDIT_THESAURI = EDIT_THESAURI;
const THESAURI_DELETED = 'THESAURI_DELETED';exports.THESAURI_DELETED = THESAURI_DELETED;
const SET_THESAURIS = 'SET_THESAURIS';exports.SET_THESAURIS = SET_THESAURIS;
const RESET_THESAURI = 'RESET_THESAURI';exports.RESET_THESAURI = RESET_THESAURI;