"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.START_UPLOAD_ATTACHMENT = exports.ATTACHMENT_RENAMED = exports.ATTACHMENT_PROGRESS = exports.ATTACHMENT_LOCAL_COMPLETE = exports.ATTACHMENT_DELETED = exports.ATTACHMENT_COMPLETE = void 0;const START_UPLOAD_ATTACHMENT = 'START_UPLOAD_ATTACHMENT';exports.START_UPLOAD_ATTACHMENT = START_UPLOAD_ATTACHMENT;
const ATTACHMENT_PROGRESS = 'ATTACHMENT_PROGRESS';exports.ATTACHMENT_PROGRESS = ATTACHMENT_PROGRESS;
const ATTACHMENT_COMPLETE = 'ATTACHMENT_COMPLETE';exports.ATTACHMENT_COMPLETE = ATTACHMENT_COMPLETE;
const ATTACHMENT_LOCAL_COMPLETE = 'ATTACHMENT_LOCAL_COMPLETE';exports.ATTACHMENT_LOCAL_COMPLETE = ATTACHMENT_LOCAL_COMPLETE;
const ATTACHMENT_DELETED = 'ATTACHMENT_DELETED';exports.ATTACHMENT_DELETED = ATTACHMENT_DELETED;
const ATTACHMENT_RENAMED = 'ATTACHMENT_RENAMED';exports.ATTACHMENT_RENAMED = ATTACHMENT_RENAMED;